/// Flutter icons CompanyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CompanyIcons
///      fonts:
///       - asset: fonts/CompanyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CompanyIcons {
  CompanyIcons._();

  static const _kFontFam = 'CompanyIcons';

  static const IconData account_balance = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData build = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData industry = const IconData(0xf275, fontFamily: _kFontFam);
}
